[book]
authors = ["zhenghaoz"]
language = "en"
multilingual = false
src = "src"
title = "Gorse Document"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/gorse-io/docs"
edit-url-template = "https://github.com/gorse-io/docs/edit/main/{path}"
